# Generated by Django 3.0.7 on 2021-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_content',
            field=models.TextField(default=''),
        ),
    ]
