# Generated by Django 3.0.7 on 2021-03-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question_title',
        ),
    ]
