# Generated by Django 3.0.7 on 2021-03-21 21:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('user_key', models.CharField(default=api.models.generate_unique_key, max_length=12, unique=True)),
            ],
        ),
    ]
