# Generated by Django 3.0.7 on 2021-02-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
