# Generated by Django 3.0.7 on 2021-02-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210214_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
