# Generated by Django 3.0.7 on 2021-02-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210215_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session',
        ),
    ]
